### ISSUE TITLE
Hay que controlar estos errores

### ISSUE THREAD

**Issue by StefAranzazu** [George-Lion/Landing-page-with-React#4]
Uno es porque hay proptypes que no están bien establecidos, el otro es porque tienen un class en lugar de className 

![Captura de pantalla (124)](https://user-images.githubusercontent.com/84442570/161815577-854e41f6-da91-429f-804f-cac75e683ff5.png)

**Comment by George-Lion** [comment]
perfecto, ya están los cambios.
